### ISSUE TITLE
Payment is not working

### ISSUE THREAD

**Issue by hanifhefaz** [anilozmen/Laravel-ECommerce-Iyzico#5]
What is wrong with payment? how can i set api key in Payment Controller? Please update the setting and guide for installation.

**Comment by anilozmen** [comment]
Guide updated. Please check.

**Comment by hanifhefaz** [comment]
still does not work bro. i can add item to cart and when i click on check out it shows me only user profile and details, but the payment section does not appear. i don't know where is the problem?

**Comment by anilozmen** [comment]
If you have followed the guide properly, it must have worked. There is no problem as soon as I checked.
